name: Sync to Hugging Face hub
on:
 push:
    branches: [main]
 workflow_dispatch:

jobs:
 sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Selectively add files or folders
        run: |
          git add requirements.txt templates app.py books.pkl popular.pkl README.md pt.pkl similarity_scores.pkl
          git commit -m "Selectively add files or folders to push"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://bhavik-punmiya:$HF_TOKEN@huggingface.co/spaces/bhavik-punmiya/book-recommendation-system main
